HIS/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(('user.urls','user'), namespace='user')),#用户模块
    url(r'^', include(('plat.urls', 'plat'), namespace='plat')),#后台管理模块

]

apps/plat/urls.py
from django.conf.urls import url
from plat.views import IndexView
urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'),
]


apps/user/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from user.views import RegisterView,LoginView,UserInfoView,LogoutView,ChangeView
urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^login$', LoginView.as_view(),name='login'),
    url(r'^logout$',LogoutView.as_view(),name='logout'),
    url(r'^change$', ChangeView.as_view(),name="change"),
    url(r'^$',UserInfoView.as_view(), name='user'),

]

apps/plat/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField
from user.models import User

class IndexGoodsBanner(BaseModel):
    #首页轮播展示商品模型类
    image = models.ImageField(upload_to='banner', verbose_name='图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')
    class Meta:
        db_table = 'df_index_banner'
        verbose_name = '首页轮播图片'
        verbose_name_plural=verbose_name
#首页分类展示模型类



class IndexPromotionBanner(BaseModel):
    #首页促销活动类
    name = models.CharField(max_length=20,verbose_name='图片名称')
    image =models.ImageField(upload_to='banner',verbose_name='图片')
    index =models.SmallIntegerField(default=0,verbose_name='展示顺序')
    class Meta:
        db_table= 'df_index_promotion'
        verbose_name='主页图片范例'
        verbose_name_plural = verbose_name

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel

class User(AbstractUser,BaseModel):
    AUTHORITY = (
        (1, '管理员'),
        (2, '普通用户'),
        (3, '审查员'),
    )
    authority = models.SmallIntegerField(default=2, choices=AUTHORITY,verbose_name='身份')
    class Meta:
        db_table = 'df_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name





apps/plat/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from plat.models import IndexGoodsBanner, IndexPromotionBanner
from django.core.paginator import Paginator
from user.models import User
from django.conf import settings
class IndexView(View):
    def get(self, request):
        # 获取首页轮播信息
        goods_banners = IndexGoodsBanner.objects.all().order_by('index')  # 排序
        # 获取首页右侧图片信息
        promotion_banners = IndexPromotionBanner.objects.all().order_by('index')

        context = {'goods_banners': goods_banners,
                   'promotion_banners': promotion_banners,}

        return render(request, 'index.html', context)

apps/user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View
import re
from user.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from utils.mixin import LoginRequiredMixin


class RegisterView(View):
    def get(self,request):
        # 显示注册界面
        return render(request, 'register.html')

    def post(self,request):
        # 进行注册处理
        # 接受数据
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        email = request.POST.get('email')
        allow = request.POST.get('allow')
        # 进行数据校验
        if not all([username, password, email]):
            # 如果数据不完整
            return render(request, 'register.html', {'errmsg': '数据不完整'})
        # 校验邮箱
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            return render(request, 'register.html', {'errmsg': '邮箱不合法'})
        # 校验协议
        if allow != 'on':
            return render(request, 'register.html', {'errmsg': '请同意协议'})
        #检验用户名是否重复
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None
        if user:
            return render(request,'register.html',{'errmsg': '用户名已存在'})
        # 进行业务处理:注册
        user = User.objects.create_user(username, email, password)
        user.is_active = 0
        user.save()
        # 返回应答,跳入
        return redirect(reverse('plat:index'))

class LoginView(View):
    def get(self, request):
        if 'username' in request.COOKIES:
            username = request.COOKIES.get('username')
            password = request.COOKIES.get('password')
            checked = 'checked'
        else:
            username = ''
            password = ''
            checked = ''
        return render(request, 'login.html',{'username':username,'checked':checked,'password':password})
    def post(self,request):
        #登录校验
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        if not all([username, password]):
            return render(request, 'login.html', {'errmsg': '数据不完整'})#接受数据
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return render(request,'login.html',{'errmsg':'无此用户'})
        pwd = user.password
        if check_password(password, pwd):
            if user.is_active:
                #记录用户登录状态
                login(request, user)
                next_url = request.GET.get('next', reverse('plat:index'))
                response = redirect(next_url)
                remember = request.POST.get('remember')
                if remember=='on':
                    response.set_cookie('username',username,max_age=7*24*3600)
                    response.set_cookie('password', password, max_age=7 * 24 * 3600)
                else:
                    response.delete_cookie('username')
                    response.delete_cookie('password')
                #获取登录后所要跳转到的地址
                #默认跳转到首页
                return response
            else:
                return render(request, 'login.html', {'errmsg': '用户未激活'})
        else:
            return render(request, 'login.html', {'errmsg': '用户名密码错误'})#校验数据业务处理


class UserInfoView(LoginRequiredMixin, View):
    def get(self, request):
        #page='/user'
        #request.user.is_authenticated()
        #如果用户登录，则为User类的实例，
        #不然为Anony_mouse_User的实例，
        #调用.is_au...方法，返回true或false
        #获取用户的个人信息
        #获取默认信息
        user = request.user
        #获取user的身份
        #获取用户的历史浏览记
        #from redis import StrictRedis
        #sr = StrictRedis(host='127.0.0.1', port='6379', db='9')
        context = {'page': 'user'}
        return render(request, 'user_center_info.html', context)
class LogoutView(View):
    def get(self,request):
        #清除用户session
        logout(request)
        return redirect(reverse('plat:index'))
class ChangeView(View):
    def get(self,request):
        user = request.user
        if not user.is_authenticated:
            return render(request, 'login.html')
        context = {'user':user,'page':'change'}
        return render(request, 'user_center_info_change.html', context)
    def post(self,request):
        user=request.user
        orcode = request.POST.get('orcode')
        code = request.POST.get('code')
        code1 = request.POST.get('code1')
        email = request.POST.get('email')
        if not user.is_authenticated:
            return render(request,'login.html')
        if not check_password(orcode,user.password):
            return render(request,'user_center_info_change.html',{'errmsg':'原密码不正确'})
        if not all([code,code1,email]):
            return render(request, 'user_center_info_change.html', {'errmsg’:‘数据不完整'})#接受数据
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            return render(request, 'user_center_info_change.html', {'errmsg': '邮箱不合法'})
        if check_password(code,user.password) and email == user.email:
            return render(request, 'user_center_info_change.html', {'errmsg': '密码和邮箱都与之前相同'})
        if code ==code1 and len(code) >=8 and len(code)<=20:
            user.set_password(code)
            user.email=email
            user.save()
        else:
            return render(request,'user_center_info_change.html',{'errmsg':'密码不符合规定或两次输入不相同'})
        return redirect(reverse('user:logout'))

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block tittle %}{% endblock tittle %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %} {% endblock topfiles %}

</head>
<body>
{% block header_con %}
	<div class="header_con">

		<div class="header">
			<div class="welcome fl">欢迎来到iship图片收集网站</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}{# 网页顶部欢迎信息块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'plat:index' %}" class="logo fl"><img src="{% static 'images/logo.png'%}"></a>
	</div>
{% endblock search_bar %}{# 网页顶部搜索框 #}
{% block body %}{# 主体内容块 #}
{% endblock body %}
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 哈尔滨工程大学船舶图片收集网站 All Rights Reserved</p>
		<p>电话：18646201718</p>
	</div>
{% block bottom %}{% endblock bottom %}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>
{# 首页 注册 登录 父模板 #}

templates/base_no_cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'plat:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
	</div>
{% endblock search_bar %}

templates/base_user_center.html
{% extends 'base_no_cart.html' %}
{% block tittle %}iship船舶图片收集网站{% endblock tittle %}
{% block page_tittle %}用户中心{% endblock page_tittle %}
{% block body %}
    	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %} class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:change' %}"{% if page == 'change' %} class="active"{% endif %}>· 修改信息</a></li>
			</ul>
		</div>
        {% block right_content %}{% endblock right_content %}
        </div>
{% endblock body %}

{# 用户中心父模板 #}

templates/index.html
{% extends 'base.html' %}
{% block tittle  %}iship数据集网站首页{% endblock tittle %}
{% load staticfiles %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}

    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">查看未审图片导航</h1>
			<ul class="navlist fl">
				<li><a href="http://www.hrbeu.edu.cn/">哈尔滨工程大学首页</a></li>
			</ul>
		</div>
	</div>
	<div class="center_con clearfix">
		<ul class="subnav fl">
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners %}
                    <li><a href="#"> <img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>
    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<a href="{% url 'plat:list_more' type.id  1 %}" class="goods_more fl" id="fruit_more">{{ type.name }}</a>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				<a href={%url 'plat:detail' banner.sku.id %}>{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
        <a href="{% url 'plat:list_more_check' type.id  1 %}" class="goods_more fr" id="fruit_more">查看{{ type.name }}的未审图片</a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url}}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a>{{ banner.sku.name }}</a></h4>
					<a><img src="{{ banner.sku.image.url }}"></a>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}

{% endblock body %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block tittle %}iship-登录{% endblock tittle %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="login_top clearfix">
		<a href="{% url 'plat:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">船舶图片收集网站</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input"  >
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username"  value="{{username}}" class="name_input" placeholder="请输入用户名">
					<div class="user_error">输入错误</div>
						<input type="password" name="pwd"  value="{{password}}" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
						<input type="checkbox"  name="remember" {{checked}}>
						<label>记住用户名和密码</label>
						<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    {{ errmsg }}
{% endblock body %}

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block tittle %}iship图片收集网站注册{% endblock tittle %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png'%}"></a>
			<div class="reg_slogan">船舶图片收集网站</div>
			<div class="reg_banner"></div>
		</div>
		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/user/register">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”iship使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block right_content %}
<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user.username}}</li>
                            <li><span>账号状态：</span>{% if user.is_active == 1 %}已激活{% else %}未激活{% endif %}</li>
                            <li><span>邮箱：</span>{{user.email}}</li>
                            <li><span>注册日期：</span>{{user.create_time}}</li>
                            <li><span>最后登录：</span>{{user.last_login}}</li>
                            <li><span>身份：</span>{% if user.authority == 2 %}普通用户{% elif  user.authority == 1 %}管理员{% else %}审查员{% endif %}</li>
                        </ul>
				</div>
		</div>
{% endblock right_content %}

templates/user_center_info_change.html
{% extends 'base_user_center.html' %}
{% block right_content %}
<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">修改密码或邮箱</h3>
						<ul class="user_info_list">
                            <form  method="post">
                                <div class="form_group3">
							<li><span>用户名：</span>{{user.username}}</li>
                        </div></br>
                        {% csrf_token %}
                                <div class="form_group3">
							<li><span>原密码：</span></li>
							<input type="password" name="orcode">
                        </div></br>
						<div class="form_group3">
							<li><span>新密码：</span></li>
							<input type="password" placeholder="密码长度必须大于7位小于21位" name="code">
                        </div></br>
                        <div class="form_group3">
							<li><span>重复新密码：</span></li>
							<input type="password" placeholder="密码长度必须大于7位小于21位" name="code1">
						</div></br>
                        <div class="form_group3">
							<li><span>邮箱：</span></li>
							<input type="text" value="{{ user.email }}" name="email">
						</div>
						<input type="submit" name="" value="提交" class="info_submit">
					    </form>
                        </ul>


				</div>
{{ errmsg }}
		</div>
{% endblock right_content %}